<a href="https://colab.research.google.com/github/beyzaatasever/Numerical-Solutions/blob/main/Linear_System_Solver_Gaussian_Elimination_with_Partial_Pivoting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# System of equations
A = np.array([[1, -1, 2, 1],
              [3, 2, 1, 4],
              [5, -8, 6, 3],
              [4, 2, 5, 3]], dtype=float)

b = np.array([1, 1, 1, -1], dtype=float)
l = len(b)  # Renamed n to l
x = np.zeros(l, float)

# Augmented matrix [A | b]
AB = np.concatenate((A, b.reshape(-1, 1)), axis=1)
print(f"Initial augmented matrix:\n{AB}")

# Partial Pivoting
i = 0
while i < l:  # Renamed n to l

    # Partial pivoting forward
    for j in range(i+1, l):  # Renamed n to l
        if abs(AB[i, i]) < abs(AB[j, i]):
            AB[[i, j]] = AB[[j, i]]

    if AB[i, i] == 0.0:
        print("Divide by zero error")
        break

    for j in range(i+1, l):  # Renamed n to l
        scaling = AB[j][i] / AB[i][i]
        AB[j] -= scaling * AB[i]
        print(f"Elimination step:\n{AB}")
    i += 1

# Backward Substitution
x[l - 1] = AB[l - 1][l] / AB[l - 1][l - 1]

for k in range(l - 2, -1, -1):
    x[k] = AB[k][l]

    for j in range(k + 1, l):  # Renamed n to l
        x[k] -= AB[k][j] * x[j]

    x[k] /= AB[k][k]

# Results
print("Solutions of the initial matrix:")
for idx, sol in enumerate(x):
    print(f"x[{idx}] is {sol}")


Initial augmented matrix:
[[ 1. -1.  2.  1.  1.]
 [ 3.  2.  1.  4.  1.]
 [ 5. -8.  6.  3.  1.]
 [ 4.  2.  5.  3. -1.]]
Elimination step:
[[ 5.  -8.   6.   3.   1. ]
 [ 0.   0.6  0.8  0.4  0.8]
 [ 3.   2.   1.   4.   1. ]
 [ 4.   2.   5.   3.  -1. ]]
Elimination step:
[[ 5.  -8.   6.   3.   1. ]
 [ 0.   0.6  0.8  0.4  0.8]
 [ 0.   6.8 -2.6  2.2  0.4]
 [ 4.   2.   5.   3.  -1. ]]
Elimination step:
[[ 5.  -8.   6.   3.   1. ]
 [ 0.   0.6  0.8  0.4  0.8]
 [ 0.   6.8 -2.6  2.2  0.4]
 [ 0.   8.4  0.2  0.6 -1.8]]
Elimination step:
[[ 5.         -8.          6.          3.          1.        ]
 [ 0.          8.4         0.2         0.6        -1.8       ]
 [ 0.          0.          0.78571429  0.35714286  0.92857143]
 [ 0.          6.8        -2.6         2.2         0.4       ]]
Elimination step:
[[ 5.         -8.          6.          3.          1.        ]
 [ 0.          8.4         0.2         0.6        -1.8       ]
 [ 0.          0.          0.78571429  0.35714286  0.92857143]
 [ 0.     